services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: database-container
